const PRODUCTS = [
{id:1,name:"Nova Headphones",category:"audio",price:129,rating:4.8,tag:"Best seller",symbol:"N",desc:"Wireless over-ear headphones with active noise cancellation and a comfortable 30-hour battery."},
{id:2,name:"Arc Mechanical Keyboard",category:"office",price:89,rating:4.7,tag:"Popular",symbol:"A",desc:"Compact mechanical keyboard with tactile switches, warm backlighting, and a clean aluminum frame."},
{id:3,name:"Focus Desk Lamp",category:"office",price:64,rating:4.6,tag:"New",symbol:"F",desc:"Adjustable LED desk lamp with three color temperatures and smooth touch controls."},
{id:4,name:"Metro Travel Pack",category:"travel",price:112,rating:4.9,tag:"Top rated",symbol:"M",desc:"A weather-resistant everyday backpack with a padded laptop compartment and smart organization."},
{id:5,name:"Orbit Wireless Mouse",category:"office",price:39,rating:4.5,tag:"Everyday",symbol:"O",desc:"Quiet wireless mouse with ergonomic shaping and multi-device connectivity."},
{id:6,name:"Pocket Speaker",category:"audio",price:59,rating:4.4,tag:"Compact",symbol:"P",desc:"Small waterproof Bluetooth speaker with surprisingly rich sound and 12-hour battery life."},
{id:7,name:"Cloud Desk Mat",category:"office",price:29,rating:4.3,tag:"Essential",symbol:"C",desc:"Soft-touch desk mat that keeps your keyboard and mouse steady while protecting your desk."},
{id:8,name:"Trail Bottle",category:"travel",price:24,rating:4.7,tag:"Favorite",symbol:"T",desc:"Double-wall insulated bottle that keeps drinks cold for a full day."}
];

function getCart(){return JSON.parse(localStorage.getItem("novamart-cart")||"[]")}
function saveCart(cart){localStorage.setItem("novamart-cart",JSON.stringify(cart));updateCartCount()}
function updateCartCount(){document.querySelectorAll(".cart-count").forEach(e=>e.textContent=getCart().reduce((n,i)=>n+i.qty,0))}
function money(n){return "$"+n.toFixed(2)}
function addToCart(id,qty=1){const p=PRODUCTS.find(x=>x.id===id),cart=getCart();const item=cart.find(x=>x.id===id);if(item)item.qty+=qty;else cart.push({id,qty});saveCart(cart);showToast(`${p.name} added to cart`)}
function showToast(msg){let t=document.querySelector(".toast");if(!t){t=document.createElement("div");t.className="toast";document.body.appendChild(t);Object.assign(t.style,{position:"fixed",bottom:"24px",right:"24px",background:"#171717",color:"#fff",padding:"13px 17px",borderRadius:"7px",fontSize:"13px",zIndex:99,boxShadow:"0 8px 25px #0003"})}t.textContent=msg;t.style.display="block";clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.style.display="none",1800)}
function productCard(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-image">${p.symbol}</div></a><div class="product-body"><div class="product-meta"><span>${p.tag}</span><span class="rating">★ ${p.rating}</span></div><a href="product.html?id=${p.id}"><div class="product-name">${p.name}</div></a><div class="product-price">${money(p.price)}</div><div class="card-actions"><a class="btn secondary" href="product.html?id=${p.id}">Details</a><button class="btn primary" onclick="addToCart(${p.id})">Add</button></div></div></article>`}
function renderFeatured(){const el=document.getElementById("featured-products");if(el)el.innerHTML=PRODUCTS.slice(0,4).map(productCard).join("")}
function initProductsPage(){const params=new URLSearchParams(location.search);const search=document.getElementById("search"),cat=document.getElementById("category"),sort=document.getElementById("sort");cat.value=params.get("category")||"all";function render(){let list=[...PRODUCTS],q=search.value.trim().toLowerCase();if(q)list=list.filter(p=>(p.name+" "+p.category+" "+p.desc).toLowerCase().includes(q));if(cat.value!=="all")list=list.filter(p=>p.category===cat.value);if(sort.value==="low")list.sort((a,b)=>a.price-b.price);if(sort.value==="high")list.sort((a,b)=>b.price-a.price);if(sort.value==="rating")list.sort((a,b)=>b.rating-a.rating);document.getElementById("product-grid").innerHTML=list.length?list.map(productCard).join(""):`<div class="empty" style="grid-column:1/-1"><h2>No products found</h2><p class="muted">Try a different search or category.</p></div>`;document.getElementById("result-count").textContent=`${list.length} product${list.length===1?"":"s"}`};[search,cat,sort].forEach(e=>e.addEventListener("input",render));render()}
function renderProductDetail(){const el=document.getElementById("product-detail"),id=Number(new URLSearchParams(location.search).get("id")),p=PRODUCTS.find(x=>x.id===id)||PRODUCTS[0];let qty=1;el.innerHTML=`<div class="detail-grid"><div class="detail-image">${p.symbol}</div><div class="detail-info"><p class="eyebrow">${p.category.toUpperCase()} · ${p.tag.toUpperCase()}</p><h1>${p.name}</h1><div class="rating">★ ${p.rating} · 120+ reviews</div><p class="detail-price">${money(p.price)}</p><p class="detail-desc">${p.desc}</p><div class="qty"><button id="minus">−</button><span id="qty">1</span><button id="plus">+</button></div><button id="detail-add" class="btn primary full">Add to cart</button><p class="fine-print">Free shipping on orders over $75 · 30-day returns</p></div></div>`;document.getElementById("minus").onclick=()=>{if(qty>1)document.getElementById("qty").textContent=--qty};document.getElementById("plus").onclick=()=>document.getElementById("qty").textContent=++qty;document.getElementById("detail-add").onclick=()=>addToCart(p.id,qty)}
function cartDetails(){return getCart().map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);return {...p,qty:i.qty,total:p.price*i.qty}})}
function totals(){const items=cartDetails(),subtotal=items.reduce((s,i)=>s+i.total,0),shipping=subtotal===0?0:subtotal>=75?0:7.95;return {items,subtotal,shipping,total:subtotal+shipping}}
function renderCart(){const el=document.getElementById("cart-page"),t=totals();if(!t.items.length){el.innerHTML=`<div class="cart-items"><div class="empty"><h2>Your cart is empty</h2><p class="muted">Find something you like and add it to your bag.</p><a class="btn primary" href="products.html">Shop products</a></div></div>`;return}el.innerHTML=`<div class="cart-items">${t.items.map(i=>`<div class="cart-item"><div class="thumb">${i.symbol}</div><div><h3>${i.name}</h3><p>${money(i.price)} each · Qty ${i.qty}</p><button class="remove" onclick="removeFromCart(${i.id})">Remove</button></div><div class="cart-price">${money(i.total)}</div></div>`).join("")}</div><aside class="summary-card"><h3>Order summary</h3><div class="summary-row"><span>Subtotal</span><b>${money(t.subtotal)}</b></div><div class="summary-row"><span>Shipping</span><b>${t.shipping?money(t.shipping):"Free"}</b></div><div class="summary-row summary-total"><span>Total</span><b>${money(t.total)}</b></div><a class="btn primary full" style="margin-top:18px" href="checkout.html">Checkout</a></aside>`}
function removeFromCart(id){saveCart(getCart().filter(i=>i.id!==id));renderCart()}
function renderCheckout(){const t=totals(),s=document.getElementById("checkout-summary");if(!t.items.length){s.innerHTML=`<h3>Your cart is empty</h3><a class="btn primary" href="products.html">Shop products</a>`;document.getElementById("checkout-form").style.display="none";return}s.innerHTML=`<h3>Order summary</h3>${t.items.map(i=>`<div class="summary-row"><span>${i.name} × ${i.qty}</span><b>${money(i.total)}</b></div>`).join("")}<div class="summary-row"><span>Shipping</span><b>${t.shipping?money(t.shipping):"Free"}</b></div><div class="summary-row summary-total"><span>Total</span><b>${money(t.total)}</b></div>`;document.getElementById("checkout-form").addEventListener("submit",e=>{e.preventDefault();localStorage.setItem("novamart-last-order",JSON.stringify({number:"NM-"+Date.now().toString().slice(-6),total:t.total}));localStorage.removeItem("novamart-cart");location.href="confirmation.html"})}
function renderConfirmation(){const o=JSON.parse(localStorage.getItem("novamart-last-order")||"null");document.getElementById("order-number").textContent=o?o.number:"NM-000000"}
function initLogin(){document.getElementById("login-form").addEventListener("submit",e=>{e.preventDefault();document.getElementById("login-message").textContent="Signed in successfully. Welcome back!";document.getElementById("login-message").style.color="#17632a"})}
